"""Removed column from job table

Revision ID: ab3d3413d8cd
Revises: 
Create Date: 2025-05-06 12:07:08.365013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3d3413d8cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['org_id'], ['id'])

    # ### end Alembic commands ###
